<option value="X" selected>Choose your location</option>
<option value="37"> 37</option>
<option value="Abelenkpe"> Abelenkpe</option>
<option value="Accra Central "> Accra Central </option>
<option value="Accra Mall"> Accra Mall </option>
<option value="Accra New Town"> Accra New Town </option>
<option value="Achimota"> Achimota </option>
<option value="Adenta"> Adenta </option>
<option value="Adjiringanor "> Adjiringanor </option>
<option value="Alajo"> Alajo </option>
<option value="Airport Hills"> Airport Hills </option>
<option value="Airport Residential"> Airport Residential </option>
<option value="American House"> American House </option>
<option value="Ashaiman"> Ashaiman </option>
<option value="Asylum Down"> Asylum Down </option>
<option value="Avenor "> Avenor </option>
<option value="Awoshie "> Awoshie </option>
<option value="Baatsona"> Baatsona </option>
<option value="Bawaleshie"> Bawaleshie</option>
<option value="Burma Camp "> Burma Camp </option>
<option value="Cantonments"> Cantonments </option>
<option value="Circle"> Circle</option>
<option value="Dansoman"> Dansoman</option>
<option value="Dzorwulu"> Dzorwulu</option>
<option value="East Legon"> East Legon</option>
<option value="Haatso"> Haatso</option>
<option value="Kanda"> Kanda</option>
<option value="Kaneshie"> Kaneshie</option>
<option value="Korle-Gornor"> Korle-Gornor</option>
<option value="Kotobabi"> Kotobabi</option>
<option value="Kwabenya"> Kwabenya </option>
<option value="Kwashieman"> Kwashieman</option>
<option value="Labadi"> Labadi</option>
<option value="Lapaz"> Lapaz</option>
<option value="Legon"> Legon</option>
<option value="Madina"> Madina</option>
<option value="Mamobi"> Mamobi</option>
<option value="Mamprobi"> Mamprobi</option>
<option value="Mataheko"> Mataheko</option>
<option value="New Achimota"> New Achimota</option>
<option value="North Lgon"> North Legon</option>
<option value="Ofankor"> Ofankor</option>
<option value="Osu"> Osu </option>
<option value="Ridge"> Ridge </option>
<option value="Sakaman"> Sakaman </option>
<option value="Sakumono"> Sakumono </option>
<option value="Spintex"> Spintex </option>
<option value="Taifa"> Taifa </option>
<option value="Tantra Hills"> Tantra Hills </option>
<option value="Tema"> Tema</option>
<option value="Tetteh Quarshie"> Tetteh Quarshie </option>
<option value="Trade Fair"> Trade Fair </option>
<option value="UPSA"> UPSA</option>
<option value="West Legon"> West Legon</option>