<option value="0" selected>Choose your option</option>
<option value="1">Accommodation</option>
<option value="2">Automobile & Parts</option>
<option value="3">Beauty Products</option>
<option value="4">Books & Stationery</option>
<option value="5">Clothing</option>
<option value="6">Education</option>
<option value="7">Electronics</option>
<option value="8">Entertainment</option>
<option value="9">Food</option>
<option value="10">Other</option>