<option value="">Choose your region</option>
<option value="AS"> Ashanti Region</option>
<option value="BA"> Brong Ahafo Region</option>
<option value="CR"> Central Region</option>
<option value="ER"> Eastern Region</option>
<option value="GR" selected> Greater Accra Region </option>
<option value="NR"> Northern Region</option>
<option value="UE"> Upper East Region</option>
<option value="UW"> Upper West Region</option>
<option value="VR"> Volta Region</option>
<option value="WR"> Western Region</option>